# Generated by Copilot
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies (minimal for CPU-only)
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libmagic1 \
    libmagic-dev \
    poppler-utils \
    wget \
    libreoffice \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies FIRST (for better caching)
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code LAST (after packages are installed)
# This ensures package installation layers are cached
COPY main.py .
COPY .env.docker .env

# Create necessary directories
RUN mkdir -p documents/uploads documents/temp documents/processed logs

# Expose port
EXPOSE 8000

# Set environment variables
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

# Health check for API
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD python -c "import requests; requests.get('http://localhost:8000/api/health')" || exit 1

# Run the unified application
CMD ["python", "main.py"]
